### ISSUE TITLE
New keys required please

### ISSUE THREAD

**Issue by johndupreez** [luisllamasbinaburo/EwelinkNET#18]
Hi 

It looks like the keys generously provided by @jlucansky on 6 Jul 2022 last year have suddenly stopped working again. These are the keys provided last year that have stopped working now:

APP_SECRET=4G91qSoboqYO4Y0XJ0LPPKIsq8reHdfa
 APP_ID=YzfeftUVcZ6twZw1OoVKPRFYTrGEg01Q

This is the reponse I now get: 
{"error":403,"msg":"Sign:oauthClient enable invalid"}

Is anyone else experiencing this, and does anyone know of new keys that can be used?

Many thanks in advance
John

**Comment by johndupreez** [comment]
I get the above response when calling GetCredentials

**Comment by YBalan** [comment]
generate AppId & AppSecret here https://dev.ewelink.cc/ just add new app

**Comment by johndupreez** [comment]
Thank you kindly. I have registered as a developer and am awaiting the review process.

**Comment by Lee337** [comment]
> Thank you kindly. I have registered as a developer and am awaiting the review process.

Did they review your application as yet?

**Comment by Lee337** [comment]
Can someone that is registered as the developer share their keys temporarily?

**Comment by johndupreez** [comment]
Hi Lee. The review was accepted this morning, so it took less than 12 hours. From there it was a very simple process to add the application and then get the App Id and App Secret. 

The new App ID and App Secret is working fine. Also to register as a personal developer is free.

**Comment by Lee337** [comment]
Thanks, I registered a few mins ago. Let's hope they get to mine soon.

**Comment by johndupreez** [comment]
They should. Enjoy Durbs!

**Comment by luisllamasbinaburo** [comment]
EwelinkNET uses a hardcoded API_ID and API_SECRET to authenticate. But Ewelink is changing their Auth process (in fact their change all their API. And the new Auth method is "weird" (not OAuth2 standard)

So you can log into official https://dev.ewelink.cc/ and generate your own API_ID and API_SECRET

I modifiy the library, so you can now use your own custom API_ID, and API_SECRET

```csharp
var ewelink = new Ewelink(Email, Password, YOUR_API_ID, YOUR_API_SECRET, Region);
var credentials = await ewelink.GetCredentials();
```

In the future, probably DEFAULT_API_ID and DEFAULT_API_SECRET will be completely remove, because probably Ewelink is going to block (or even ban user) fast.

More info in this active issues from the JS equivalent of EwelinkNET
- https://github.com/skydiver/ewelink-api/issues/220
- https://github.com/skydiver/ewelink-api/issues/221

**Comment by johndupreez** [comment]
Thanks. The process of adding an APP then getting your own API_ID and API_SECRET works fine, so closing the issue.

**Comment by soki2001** [comment]
looks like get info works fine but SET on or off is not working for me
